# Generated by Django 5.1.1 on 2024-10-02 23:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Порода',
            },
        ),
        migrations.CreateModel(
            name='Kitty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('color', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Цвет котёнка')),
                ('age', models.IntegerField(db_index=True, help_text='Возраст котёнка (в полных месяцах)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Возраст котёнка')),
                ('description', models.TextField(default='Описание отсутсвует', help_text='Описание котёнка. (Желательно подробное)', verbose_name='Описание котёнка')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.breed', verbose_name='Порода котёнка')),
            ],
            options={
                'verbose_name': 'Котёнок',
                'verbose_name_plural': 'Породы',
            },
        ),
    ]
